name: mustache_generator_example
description: A starting point for Dart libraries or applications.
deploy_to: none
homepage: https://github.com/juancastillo0/template_generator

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  mobx: ^2.0.7+5
  mustache_generator:
    path: ..

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
