targets:
  $default:
    builders:
      mustache_generator|mustache_lib_gen:
        enabled: true

builders:
  mustache_lib_gen:
    # library URI containing the builder - maps to `lib/member_count_library_generator.dart`
    import: "package:mustache_generator/mustache_generator.dart"
    # Name of the function in the above library to call.
    builder_factories: ["mustacheLibGen"]
    # The mapping from the source extension to the generated file extension
    build_extensions: { ".dart": [".mustache.dart"] }
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the output directly into the package, not to a hidden cache dir
    build_to: source
