name: mustache_generator
description: Generate files from Dart code annotations and Mustache templates
version: 0.0.1
homepage: https://github.com/juancastillo0/template_generator

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  build: ^2.3.0
  mustache_template: ^2.0.0
  source_gen: ^1.2.2

  analyzer: ^5.11.0
  glob: ^2.1.0
  dart_style: ^2.2.3
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
